const express = require('express')
const router = express.Router()
const isAuth = require('../middleware/isAuth')
const userDetails = require('../controllers/userDetails')
const uploadProfile = require('../controllers/uploadProfile')
const editProfile = require('../controllers/editProfile')
const getAllProduct = require('../controllers/getAllProduct')
const addToCart = require('../controllers/addToCart')
const deleteFromCart = require('../controllers/deleteFromCart')
const cartIncrement = require('../controllers/cartIncrement')
const cartDecrement = require('../controllers/cartDecrement')
const addNewCard = require('../controllers/addNewCard')
const deleteCard = require('../controllers/deleteCard')
const updateCard = require('../controllers/updateCard')
const addShippingAddress = require('../controllers/addShippingAddress')
const deleteShippingAddress = require('../controllers/deleteShippingAddress')
const updateShippingAddress = require('../controllers/updateShippingAddress')
const order = require('../controllers/order')
const cancelOrder = require('../controllers/cancelOrder')
const selectShippingAddress = require('../controllers/selectShippingAddress')
const selectPaymentCard = require('../controllers/selectPaymentCard')

router.get('/userDetails', isAuth, userDetails)
router.post('/editProfile', isAuth, editProfile)
router.post('/uploadProfile', uploadProfile)
router.get('/getAllProduct', isAuth, getAllProduct)
router.post('/addToCart', isAuth, addToCart)
router.post('/deleteFromCart', isAuth, deleteFromCart)
router.post('/cartIncrement', isAuth, cartIncrement)
router.post('/cartDecrement', isAuth, cartDecrement)
router.post('/addNewCard', isAuth, addNewCard)
router.post('/deleteCard', isAuth, deleteCard)
router.post('/updateCard', isAuth, updateCard)
router.post('/addShippingAddress', isAuth, addShippingAddress)
router.post('/deleteShippingAddress', isAuth, deleteShippingAddress)
router.post('/updateShippingAddress', isAuth, updateShippingAddress)
router.post('/order', isAuth, order)
router.post('/cancelOrder', isAuth, cancelOrder)
router.post('/selectShippingAddress', isAuth, selectShippingAddress)
router.post('/selectPaymentCard', isAuth, selectPaymentCard)

module.exports = router